server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
# 数据库连接配置
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default: # todo  修改成自己的密码
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/bvt"
    debug: true

redis:
  url: 127.0.0.1:6379

jwt:
  tokenExpire: 30 # token有效时长(分钟)
  signingKey: gotemplate # 签名使用的key
