// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserMessage is the golang structure of table kcode_user_message for DAO operations like Where/Data.
type KcodeUserMessage struct {
	g.Meta     `orm:"table:kcode_user_message, do:true"`
	Id         interface{} //
	UidReceive interface{} // 接收消息的用户id
	UidSend    interface{} // 发送消息的用户id
	Type       interface{} // 消息分类
	Title      interface{} // 发送的标题
	Content    interface{} // 消息内容
	Status     interface{} // 状态
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	ReadTime   interface{} // 阅读时间
}
