// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserInfo is the golang structure of table kcode_user_info for DAO operations like Where/Data.
type KcodeUserInfo struct {
	g.Meta `orm:"table:kcode_user_info, do:true"`
	UserId interface{} //
	Sex    interface{} // 0  保密 1 男 2女
}
