// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserBonusCensus is the golang structure of table kcode_user_bonus_census for DAO operations like Where/Data.
type KcodeUserBonusCensus struct {
	g.Meta       `orm:"table:kcode_user_bonus_census, do:true"`
	Id           interface{} // 主键
	UserId       interface{} // 用户id
	MoneyType    interface{} // 币种类型
	ZhituiBonus  interface{} // 直推奖励
	TeamBonus    interface{} // 团队奖励
	WholeBonus   interface{} // 全网加权分红
	EquityBonus  interface{} // 权益分红
	ReleaseBonus interface{} // 释放收益
	PjBonus      interface{} // 平级奖
}
