// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeInvestRounds is the golang structure of table kcode_invest_rounds for DAO operations like Where/Data.
type KcodeInvestRounds struct {
	g.Meta    `orm:"table:kcode_invest_rounds, do:true"`
	Id        interface{} //
	StartTime interface{} // 开始时间
	EndTime   interface{} // 结束时间
	IsLock    interface{} // 1默认锁住 排队处理完再恢复0
	AddTime   interface{} // 添加时间
	MaxUsdt   interface{} // 每轮剂量
}
