// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeInvestPledgeOrder is the golang structure of table kcode_invest_pledge_order for DAO operations like Where/Data.
type KcodeInvestPledgeOrder struct {
	g.Meta          `orm:"table:kcode_invest_pledge_order, do:true"`
	OrderId         interface{} //
	AddTime         interface{} //
	OrderSn         interface{} //
	UserId          interface{} //
	PayStatus       interface{} // 1已支付0未支付
	MoneyType       interface{} //
	OrderMoney      interface{} // 投资金额
	OrderType       interface{} // 1质押 2激活
	ExpandNum       interface{} // 收益倍数
	TokenDayMoney   interface{} // 今日收益
	TokenCountMoney interface{} // 累计收益
	ReturnCountDay  interface{} // 累计释放天数
	SetDayTime      interface{} // 最后释放时间
	Status          interface{} // 1质押中 0闲置中 2已赎回 3已分红完
	PayHash         interface{} // 付款hash
	PayTime         interface{} // 付款时间
	RedeTime        interface{} // 赎回时间
	HashRemark      interface{} //
	TotalIncome     interface{} // 翻倍后总收益
	TopOrderId      interface{} //
	ResidualIncome  interface{} // 剩余收益
	OrderUsdt       interface{} // 实际投资USDT
	Hash            interface{} // 付款hash
	CoinPrice       interface{} // 当前比价
	UsdtMoney       interface{} // 新版记录（仅页面回显用到）
	TotalIncomeUsdt interface{} // 总收益 U
	ResidualUsdt    interface{} // 剩余收益 u
	Line            interface{} // 1排队中 0未排队
	PaiTime         interface{} // 排队时间
}
