// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeNewsType is the golang structure of table kcode_news_type for DAO operations like Where/Data.
type KcodeNewsType struct {
	g.Meta      `orm:"table:kcode_news_type, do:true"`
	Id          interface{} //
	Name        interface{} // 分类名称
	Pid         interface{} // 父id
	Status      interface{} // 状态 0 不显示  1显示
	Sort        interface{} // 排序序号
	SeoTitle    interface{} // seo
	Keywords    interface{} // keywords
	Description interface{} // description
	Path        interface{} // 节点
	Pic         interface{} // 图片
}
