// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeTrend is the golang structure of table kcode_trend for DAO operations like Where/Data.
type KcodeTrend struct {
	g.Meta    `orm:"table:kcode_trend, do:true"`
	Id        interface{} //
	MoneyType interface{} //
	Today     interface{} //
	Hour      interface{} //
	V         interface{} // 开盘价
}
