// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminIcon is the golang structure of table kcode_admin_icon for DAO operations like Where/Data.
type KcodeAdminIcon struct {
	g.Meta     `orm:"table:kcode_admin_icon, do:true"`
	Id         interface{} //
	Name       interface{} // 图标名称
	Url        interface{} // 图标css地址
	Prefix     interface{} // 图标前缀
	FontFamily interface{} // 字体名
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	Status     interface{} // 状态
}
