// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserMoneyType is the golang structure of table kcode_user_money_type for DAO operations like Where/Data.
type KcodeUserMoneyType struct {
	g.Meta          `orm:"table:kcode_user_money_type, do:true"`
	Id              interface{} //
	Icon            interface{} // 币种图标
	Name            interface{} // 币种英文标识
	EnName          interface{} // 币种英文名字
	CnName          interface{} // 币种中文名字
	IsSystem        interface{} // 系统变量
	IsTransfer      interface{} // 是否允许转账
	IsAdmRecharge   interface{} // 是否允许后台充值
	IsUserRecharge  interface{} // 是否允许用户充值
	IsAtm           interface{} // 是否可以提现
	ExchangeRate    interface{} // 币价（$）
	IsExchange      interface{} // 是否可以兑换
	Status          interface{} // 状态 0禁用  1启用
	ContractAddress interface{} // 代币合约地址
	MinAtmMoney     interface{} // 最低提现金额
	AtmFee          interface{} // 提现手续费
	AtmTips         interface{} // 提现说明
	TokenAbi        interface{} // 币种的token_abi
	WithdrawRatio   interface{} // 可提现比例
	WithdrawDays    interface{} // 提现间隔天数
	Decimals        interface{} // 精度
	WalletAddress   interface{} // 收款钱包地址
	AutoMoeny       interface{} // 自动审核
	MaxAtmMoney     interface{} // 最高提现金额
	Date1           interface{} // 提现开始时间
	Date2           interface{} // 提现结束时间
	IsSell          interface{} // 是否开启出售
	SellPrice       interface{} // 最低多少起售
	WithdrawAddress interface{} // 提现钱包地址
	WithdrawKey     interface{} // 提现钱包加密私钥
	Port            interface{} // node服务断开（不能重复）
	Zhou            interface{} // 周提现
	RangeAbility    interface{} // 涨跌幅
	TransactionPair interface{} // 交易对
}
