// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodePayTemp is the golang structure of table kcode_pay_temp for DAO operations like Where/Data.
type KcodePayTemp struct {
	g.Meta          `orm:"table:kcode_pay_temp, do:true"`
	Id              interface{} //
	UserId          interface{} //
	AddTime         interface{} //
	Method          interface{} //
	Param           interface{} //
	Status          interface{} //
	Money           interface{} //
	ContractAddress interface{} // 合约地址
	WalletAddress   interface{} // 收款钱包
	Hash            interface{} // 此hash前端传2时有
}
