// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminRole is the golang structure of table kcode_admin_role for DAO operations like Where/Data.
type KcodeAdminRole struct {
	g.Meta        `orm:"table:kcode_admin_role, do:true"`
	Id            interface{} // 角色id
	Pid           interface{} // 上级角色
	Name          interface{} // 角色名称
	Description   interface{} // 角色描述
	MenuAuth      interface{} // 菜单权限
	Sort          interface{} // 排序
	CreateTime    interface{} // 创建时间
	UpdateTime    interface{} // 更新时间
	Status        interface{} // 状态
	Access        interface{} // 是否可登录后台
	DefaultModule interface{} // 默认访问模块
}
