// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeSmsEmailLog is the golang structure of table kcode_sms_email_log for DAO operations like Where/Data.
type KcodeSmsEmailLog struct {
	g.Meta       `orm:"table:kcode_sms_email_log, do:true"`
	Id           interface{} // 记录ID
	Email        interface{} // 用户邮箱
	Scene        interface{} // 发送场景 1:用户注册,2:找回登录密码,3:找回资金密码,3:客户下单,4:客户支付,5:商家发货,6:实名验证' 7:退款成功
	Status       interface{} // 发送状态
	Code         interface{} // 验证码
	Msg          interface{} // 发送短信内容
	AddTime      interface{} // 添加时间
	ValidityTime interface{} // 有效期
	Ip           interface{} //
	ErrorMsg     interface{} // 发送短信异常内容
}
