// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeWithdrawals is the golang structure of table kcode_withdrawals for DAO operations like Where/Data.
type KcodeWithdrawals struct {
	g.Meta       `orm:"table:kcode_withdrawals, do:true"`
	Id           interface{} // id
	UserId       interface{} // 用户id
	AtmMoney     interface{} // 申请金额
	AtmMoneyType interface{} // 币种类型
	TaxFee       interface{} // 税收手续费
	Money        interface{} // 到账金额
	Status       interface{} // 状态：0申请中1审核通过2审核失败
	TransStatus  interface{} // '待确认','已到账','到账失败'
	CreateTime   interface{} // 申请时间
	CheckTime    interface{} // 审核时间
	RefuseTime   interface{} // 拒绝时间
	AtmAddress   interface{} // 转账钱包地址
	ChainName    interface{} // 链名称
	AtmQrCode    interface{} // 二维码
	Hash         interface{} //
	Chain        interface{} // 链ID
	ErrorMsg     interface{} //
}
