// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserRecharge is the golang structure of table kcode_user_recharge for DAO operations like Where/Data.
type KcodeUserRecharge struct {
	g.Meta         `orm:"table:kcode_user_recharge, do:true"`
	Id             interface{} //
	UserId         interface{} //
	PayAddress     interface{} // 客户钱包地址
	WalletAddress  interface{} // 商家收款钱包地址
	Hash           interface{} // hash
	CreateTime     interface{} // 创建时间
	Status         interface{} // 是否已经处理 0 未处理 1 已经处理 2处理失败
	Money          interface{} // 充值金额
	SetStatus      interface{} // 脚本执行装0未执行， 1已执行
	UpdateTime     interface{} // 审核时间
	Content        interface{} // 备注
	PayImg         interface{} // 打款凭证
	RechargeStatus interface{} // 充值状态（0=待确认,1'已到账',2'到账失败'）
	MoneyType      interface{} // 币种类型
}
