// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminAccess is the golang structure of table kcode_admin_access for DAO operations like Where/Data.
type KcodeAdminAccess struct {
	g.Meta `orm:"table:kcode_admin_access, do:true"`
	Module interface{} // 模型名称
	Group  interface{} // 权限分组标识
	Uid    interface{} // 用户id
	Nid    interface{} // 授权节点id
	Tag    interface{} // 分组标签
}
