// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserGroup is the golang structure of table kcode_user_group for DAO operations like Where/Data.
type KcodeUserGroup struct {
	g.Meta           `orm:"table:kcode_user_group, do:true"`
	GroupId          interface{} // 级别id
	GroupName        interface{} // 级别名称
	UpZtNum          interface{} // 升级需要的直推人数
	ZtBuyNum         interface{} // 直推业绩
	BuyNum           interface{} // 升级需要的个人业绩
	TeamBuyNum       interface{} // 升级需要的团队业绩
	UpTeamNum        interface{} // 升级需要的团队人数
	UpTeamGroup      interface{} // 升级需要的团队会员级别要求
	TeamBonus        interface{} // 团队奖比例
	ZtValidAccount   interface{} // 直推有效账号人数
	ShareProfits     interface{} // 分红
	CreateTime       interface{} // 创建时间
	UpdateTime       interface{} // 最后更新时间
	TeamProfitsFloor interface{} // 团队奖层级奖励
	ExchangeFee      interface{} // 内部交易所手续费
	RewardRules      interface{} // 奖励规则
	Logo             interface{} //
}
