// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminLog is the golang structure of table kcode_admin_log for DAO operations like Where/Data.
type KcodeAdminLog struct {
	g.Meta     `orm:"table:kcode_admin_log, do:true"`
	Id         interface{} // 主键
	ActionId   interface{} // 行为id
	UserId     interface{} // 执行用户id
	ActionIp   interface{} // 执行行为者ip
	Model      interface{} // 触发行为的表
	RecordId   interface{} // 触发行为的数据id
	Remark     interface{} // 日志备注
	Status     interface{} // 状态
	CreateTime interface{} // 执行行为的时间
}
