// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminAttachment is the golang structure of table kcode_admin_attachment for DAO operations like Where/Data.
type KcodeAdminAttachment struct {
	g.Meta     `orm:"table:kcode_admin_attachment, do:true"`
	Id         interface{} //
	Uid        interface{} // 用户id
	Name       interface{} // 文件名
	Module     interface{} // 模块名，由哪个模块上传的
	Path       interface{} // 文件路径
	Thumb      interface{} // 缩略图路径
	Url        interface{} // 文件链接
	Mime       interface{} // 文件mime类型
	Ext        interface{} // 文件类型
	Size       interface{} // 文件大小
	Md5        interface{} // 文件md5
	Sha1       interface{} // sha1 散列值
	Driver     interface{} // 上传驱动
	Download   interface{} // 下载次数
	CreateTime interface{} // 上传时间
	UpdateTime interface{} // 更新时间
	Sort       interface{} // 排序
	Status     interface{} // 状态
	Width      interface{} // 图片宽度
	Height     interface{} // 图片高度
}
