// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAd is the golang structure of table kcode_ad for DAO operations like Where/Data.
type KcodeAd struct {
	g.Meta     `orm:"table:kcode_ad, do:true"`
	AdId       interface{} // 广告id
	Pid        interface{} // 广告位置ID
	MediaType  interface{} // 广告类型
	AdName     interface{} // 广告名称
	AdLink     interface{} // 链接地址
	AdCode     interface{} // 图片地址
	StartTime  interface{} // 投放时间
	EndTime    interface{} // 结束时间
	LinkMan    interface{} // 添加人
	LinkEmail  interface{} // 添加人邮箱
	LinkPhone  interface{} // 添加人联系电话
	ClickCount interface{} // 点击量
	Enabled    interface{} // 是否显示
	Orderby    interface{} // 排序
	Target     interface{} // 是否开启浏览器新窗口
	Bgcolor    interface{} // 背景颜色
}
