// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminUser is the golang structure of table kcode_admin_user for DAO operations like Where/Data.
type KcodeAdminUser struct {
	g.Meta        `orm:"table:kcode_admin_user, do:true"`
	Id            interface{} //
	Username      interface{} // 用户名
	Nickname      interface{} // 昵称
	Password      interface{} // 密码
	Email         interface{} // 邮箱地址
	EmailBind     interface{} // 是否绑定邮箱地址
	Mobile        interface{} // 手机号码
	MobileBind    interface{} // 是否绑定手机号码
	Avatar        interface{} // 头像
	Money         interface{} // 余额
	Score         interface{} // 积分
	Role          interface{} // 主角色ID
	Roles         interface{} // 副角色ID
	Group         interface{} // 部门id
	SignupIp      interface{} // 注册ip
	CreateTime    interface{} // 创建时间
	UpdateTime    interface{} // 更新时间
	LastLoginTime interface{} // 最后一次登录时间
	LastLoginIp   interface{} // 登录ip
	Sort          interface{} // 排序
	Status        interface{} // 状态：0禁用，1启用
	Secret        interface{} // 谷歌验证器秘钥
}
