// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserToken is the golang structure of table kcode_user_token for DAO operations like Where/Data.
type KcodeUserToken struct {
	g.Meta       `orm:"table:kcode_user_token, do:true"`
	Id           interface{} //
	UserId       interface{} // 用户userid
	Token        interface{} //
	LoginTime    interface{} // 登录时间
	LoginIp      interface{} // 登录IP地址
	LoginOs      interface{} // 登录操作系统
	LoginBrowser interface{} // 登录浏览器
	ExpireTime   interface{} // 有效期
	LoginType    interface{} // 登录类型 0 未知 1 网页 2.移动端网页 3.app
}
