// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserLog is the golang structure of table kcode_user_log for DAO operations like Where/Data.
type KcodeUserLog struct {
	g.Meta  `orm:"table:kcode_user_log, do:true"`
	Id      interface{} //
	UserId  interface{} //
	Msg     interface{} // 用户操作信息
	AddTime interface{} // 添加时间
}
