// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserMoney is the golang structure of table kcode_user_money for DAO operations like Where/Data.
type KcodeUserMoney struct {
	g.Meta           `orm:"table:kcode_user_money, do:true"`
	Id               interface{} //
	UserId           interface{} //
	AMoney           interface{} //
	UsdtMoney        interface{} //
	BMoney           interface{} //
	SetLastTime      interface{} // 最后结算的时间
	SetLastDate      interface{} // 最后结算的日期
	SetDayTime       interface{} // 订单下次可以结算的日期
	ReturnCountDay   interface{} // 已经发放天数
	ReturnCountMoney interface{} // 发放总额
	ReturnMaxDay     interface{} // 发放天数
	Status           interface{} // 私募奖励发放是否到期
	MoneyId          interface{} // 币种id
	Balance          interface{} //
}
