// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserMoneyLog is the golang structure of table kcode_user_money_log for DAO operations like Where/Data.
type KcodeUserMoneyLog struct {
	g.Meta        `orm:"table:kcode_user_money_log, do:true"`
	LogId         interface{} // 自增编号
	UserId        interface{} // 用户user_id
	MoneyType     interface{} // 币种类型 关联money_type 表
	Money         interface{} // 变化的金额
	MoneyAction   interface{} // 增加还是减少 默认+
	Balance       interface{} // 余下额度
	Messages      interface{} // 交易信息
	LangVal       interface{} // 语言键值
	MessagesLang  interface{} // 语言内容
	AddTime       interface{} // 添加时间
	ParentId      interface{} // 父ID
	Status        interface{} // 状态 0 未成功 1成功
	PayTime       interface{} // 支付时间
	OperationType interface{} // 操作类型
	BonusType     interface{} // 奖金类型，1直推奖励 2团队奖励3全网加权分红4权益分红
	EndTime       interface{} // 结算时间
	CoinPrice     interface{} // 当前币价
	Usdt          interface{} // usdt
}
