// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminConfig is the golang structure of table kcode_admin_config for DAO operations like Where/Data.
type KcodeAdminConfig struct {
	g.Meta     `orm:"table:kcode_admin_config, do:true"`
	Id         interface{} //
	Name       interface{} // 名称
	Title      interface{} // 标题
	Group      interface{} // 配置分组
	Type       interface{} // 类型
	Value      interface{} // 配置值
	Options    interface{} // 配置项
	Tips       interface{} // 配置提示
	AjaxUrl    interface{} // 联动下拉框ajax地址
	NextItems  interface{} // 联动下拉框的下级下拉框名，多个以逗号隔开
	Param      interface{} // 联动下拉框请求参数名
	Format     interface{} // 格式，用于格式文本
	Table      interface{} // 表名，只用于快速联动类型
	Level      interface{} // 联动级别，只用于快速联动类型
	Key        interface{} // 键字段，只用于快速联动类型
	Option     interface{} // 值字段，只用于快速联动类型
	Pid        interface{} // 父级id字段，只用于快速联动类型
	Ak         interface{} // 百度地图appkey
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	Sort       interface{} // 排序
	Status     interface{} // 状态：0禁用，1启用
}
