// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeJobOrder is the golang structure of table kcode_job_order for DAO operations like Where/Data.
type KcodeJobOrder struct {
	g.Meta     `orm:"table:kcode_job_order, do:true"`
	OrderId    interface{} //
	OrderSn    interface{} //
	UserId     interface{} //
	JobId      interface{} // 节点ID
	AddTime    interface{} // 添加时间
	Status     interface{} // 0排队中1待审核2已通过
	UpdateTime interface{} // 修改时间
}
