// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserUpLog is the golang structure of table kcode_user_up_log for DAO operations like Where/Data.
type KcodeUserUpLog struct {
	g.Meta         `orm:"table:kcode_user_up_log, do:true"`
	Id             interface{} //
	OldGroupId     interface{} //
	NewGroupId     interface{} //
	UserId         interface{} // 用户user_id
	ZtNum          interface{} // 直推人数
	RefereeNum     interface{} // 推荐的数量
	BuyNum         interface{} // 个人业绩
	ZtBuyNum       interface{} // 直推业绩
	CommunityMoney interface{} // 小区业绩
	Title          interface{} // 标题
	Content        interface{} // 内容
	AddTime        interface{} // 添加时间
}
