// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserGroupBonus is the golang structure of table kcode_user_group_bonus for DAO operations like Where/Data.
type KcodeUserGroupBonus struct {
	g.Meta     `orm:"table:kcode_user_group_bonus, do:true"`
	Id         interface{} //
	GroupId    interface{} // 级别
	Floor      interface{} // 层级
	BonusMoney interface{} // 奖金比例
}
