// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserLoginLog is the golang structure of table kcode_user_login_log for DAO operations like Where/Data.
type KcodeUserLoginLog struct {
	g.Meta       `orm:"table:kcode_user_login_log, do:true"`
	LogId        interface{} // 自动编号log_id
	UserId       interface{} // 用户User_id
	Username     interface{} // 登录用户名字
	LoginTime    interface{} // 登录时间
	LoginIp      interface{} // 登录IP地址
	LoginType    interface{} // 登录类型
	LoginOs      interface{} // 登录系统信息
	LoginBrowser interface{} //
	LoginMsg     interface{} // 登录提示信息
	Status       interface{} //
}
