// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminHook is the golang structure of table kcode_admin_hook for DAO operations like Where/Data.
type KcodeAdminHook struct {
	g.Meta      `orm:"table:kcode_admin_hook, do:true"`
	Id          interface{} //
	Name        interface{} // 钩子名称
	Plugin      interface{} // 钩子来自哪个插件
	Description interface{} // 钩子描述
	System      interface{} // 是否为系统钩子
	CreateTime  interface{} // 创建时间
	UpdateTime  interface{} // 更新时间
	Status      interface{} // 状态
}
