// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminModule is the golang structure of table kcode_admin_module for DAO operations like Where/Data.
type KcodeAdminModule struct {
	g.Meta       `orm:"table:kcode_admin_module, do:true"`
	Id           interface{} //
	Name         interface{} // 模块名称（标识）
	Title        interface{} // 模块标题
	Icon         interface{} // 图标
	Description  interface{} // 描述
	Author       interface{} // 作者
	AuthorUrl    interface{} // 作者主页
	Config       interface{} // 配置信息
	Access       interface{} // 授权配置
	Version      interface{} // 版本号
	Identifier   interface{} // 模块唯一标识符
	SystemModule interface{} // 是否为系统模块
	CreateTime   interface{} // 创建时间
	UpdateTime   interface{} // 更新时间
	Sort         interface{} // 排序
	Status       interface{} // 状态
}
