// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminIconList is the golang structure of table kcode_admin_icon_list for DAO operations like Where/Data.
type KcodeAdminIconList struct {
	g.Meta `orm:"table:kcode_admin_icon_list, do:true"`
	Id     interface{} //
	IconId interface{} // 所属图标id
	Title  interface{} // 图标标题
	Class  interface{} // 图标类名
	Code   interface{} // 图标关键词
}
