// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserJob is the golang structure of table kcode_user_job for DAO operations like Where/Data.
type KcodeUserJob struct {
	g.Meta           `orm:"table:kcode_user_job, do:true"`
	GroupId          interface{} // 级别id
	GroupName        interface{} // 级别名称
	Zhituibili       interface{} // 直推比例
	GroupNameEn      interface{} // 级别名称
	ContentEn        interface{} // 内容
	Price            interface{} // 节点价格
	UsdtBonus        interface{} // 节点分红余额
	EndBonusTime     interface{} // 最后分红时间
	Num              interface{} // 名额人数
	Content          interface{} // 内容
	Count            interface{} // 已购买数量
	InvestMoney      interface{} // 质押金额
	NetworkBonus     interface{} // 全网加权分红百分比
	EquityBonus      interface{} // 权益分红百分比
	OldGroupId       interface{} //
	Logo             interface{} //
	NetworkBonusPond interface{} // 全网加权分红池子
	EquityBonusPond  interface{} // 权益分红池子
	PjBonus          interface{} // 平级奖
	Status           interface{} // 1开放0不开放
}
