// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminPlugin is the golang structure of table kcode_admin_plugin for DAO operations like Where/Data.
type KcodeAdminPlugin struct {
	g.Meta      `orm:"table:kcode_admin_plugin, do:true"`
	Id          interface{} //
	Name        interface{} // 插件名称
	Title       interface{} // 插件标题
	Icon        interface{} // 图标
	Description interface{} // 插件描述
	Author      interface{} // 作者
	AuthorUrl   interface{} // 作者主页
	Config      interface{} // 配置信息
	Version     interface{} // 版本号
	Identifier  interface{} // 插件唯一标识符
	Admin       interface{} // 是否有后台管理
	CreateTime  interface{} // 安装时间
	UpdateTime  interface{} // 更新时间
	Sort        interface{} // 排序
	Status      interface{} // 状态
}
