// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdPosition is the golang structure of table kcode_ad_position for DAO operations like Where/Data.
type KcodeAdPosition struct {
	g.Meta        `orm:"table:kcode_ad_position, do:true"`
	Id            interface{} // 表id
	PositionName  interface{} // 广告位置名称
	AdWidth       interface{} // 广告位宽度
	AdHeight      interface{} // 广告位高度
	PositionDesc  interface{} // 广告描述
	PositionStyle interface{} // 模板
	IsOpen        interface{} // 0关闭1开启
}
