// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeInvestFuel is the golang structure of table kcode_invest_fuel for DAO operations like Where/Data.
type KcodeInvestFuel struct {
	g.Meta          `orm:"table:kcode_invest_fuel, do:true"`
	Id              interface{} //
	AddTime         interface{} //
	UserId          interface{} //
	TokenDayMoney   interface{} // 今日收益
	TokenCountMoney interface{} // 累计收益
	ReturnCountDay  interface{} // 累计释放天数
	SetDayTime      interface{} // 最后释放时间
	TotalIncome     interface{} // 总收益
	ResidualIncome  interface{} // 剩余收益
	UpdateTime      interface{} //
	ProgressBar     interface{} // 进度条
}
