// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeInvestRoundsDao is the data access object for table kcode_invest_rounds.
type KcodeInvestRoundsDao struct {
	table   string                   // table is the underlying table name of the DAO.
	group   string                   // group is the database configuration group name of current DAO.
	columns KcodeInvestRoundsColumns // columns contains all the column names of Table for convenient usage.
}

// KcodeInvestRoundsColumns defines and stores column names for table kcode_invest_rounds.
type KcodeInvestRoundsColumns struct {
	Id        string //
	StartTime string // 开始时间
	EndTime   string // 结束时间
	IsLock    string // 1默认锁住 排队处理完再恢复0
	AddTime   string // 添加时间
	MaxUsdt   string // 每轮剂量
}

// kcodeInvestRoundsColumns holds the columns for table kcode_invest_rounds.
var kcodeInvestRoundsColumns = KcodeInvestRoundsColumns{
	Id:        "id",
	StartTime: "start_time",
	EndTime:   "end_time",
	IsLock:    "is_lock",
	AddTime:   "add_time",
	MaxUsdt:   "max_usdt",
}

// NewKcodeInvestRoundsDao creates and returns a new DAO object for table data access.
func NewKcodeInvestRoundsDao() *KcodeInvestRoundsDao {
	return &KcodeInvestRoundsDao{
		group:   "default",
		table:   "kcode_invest_rounds",
		columns: kcodeInvestRoundsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KcodeInvestRoundsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KcodeInvestRoundsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KcodeInvestRoundsDao) Columns() KcodeInvestRoundsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KcodeInvestRoundsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KcodeInvestRoundsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KcodeInvestRoundsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
