// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdPositionDao is the data access object for table kcode_ad_position.
type KcodeAdPositionDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns KcodeAdPositionColumns // columns contains all the column names of Table for convenient usage.
}

// KcodeAdPositionColumns defines and stores column names for table kcode_ad_position.
type KcodeAdPositionColumns struct {
	Id            string // 表id
	PositionName  string // 广告位置名称
	AdWidth       string // 广告位宽度
	AdHeight      string // 广告位高度
	PositionDesc  string // 广告描述
	PositionStyle string // 模板
	IsOpen        string // 0关闭1开启
}

// kcodeAdPositionColumns holds the columns for table kcode_ad_position.
var kcodeAdPositionColumns = KcodeAdPositionColumns{
	Id:            "id",
	PositionName:  "position_name",
	AdWidth:       "ad_width",
	AdHeight:      "ad_height",
	PositionDesc:  "position_desc",
	PositionStyle: "position_style",
	IsOpen:        "is_open",
}

// NewKcodeAdPositionDao creates and returns a new DAO object for table data access.
func NewKcodeAdPositionDao() *KcodeAdPositionDao {
	return &KcodeAdPositionDao{
		group:   "default",
		table:   "kcode_ad_position",
		columns: kcodeAdPositionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KcodeAdPositionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KcodeAdPositionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KcodeAdPositionDao) Columns() KcodeAdPositionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KcodeAdPositionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KcodeAdPositionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KcodeAdPositionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
