// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeUserInfoDao is the data access object for table kcode_user_info.
type KcodeUserInfoDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns KcodeUserInfoColumns // columns contains all the column names of Table for convenient usage.
}

// KcodeUserInfoColumns defines and stores column names for table kcode_user_info.
type KcodeUserInfoColumns struct {
	UserId string //
	Sex    string // 0  保密 1 男 2女
}

// kcodeUserInfoColumns holds the columns for table kcode_user_info.
var kcodeUserInfoColumns = KcodeUserInfoColumns{
	UserId: "user_id",
	Sex:    "sex",
}

// NewKcodeUserInfoDao creates and returns a new DAO object for table data access.
func NewKcodeUserInfoDao() *KcodeUserInfoDao {
	return &KcodeUserInfoDao{
		group:   "default",
		table:   "kcode_user_info",
		columns: kcodeUserInfoColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KcodeUserInfoDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KcodeUserInfoDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KcodeUserInfoDao) Columns() KcodeUserInfoColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KcodeUserInfoDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KcodeUserInfoDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KcodeUserInfoDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
