// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdDao is the data access object for table kcode_ad.
type KcodeAdDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns KcodeAdColumns // columns contains all the column names of Table for convenient usage.
}

// KcodeAdColumns defines and stores column names for table kcode_ad.
type KcodeAdColumns struct {
	AdId       string // 广告id
	Pid        string // 广告位置ID
	MediaType  string // 广告类型
	AdName     string // 广告名称
	AdLink     string // 链接地址
	AdCode     string // 图片地址
	StartTime  string // 投放时间
	EndTime    string // 结束时间
	LinkMan    string // 添加人
	LinkEmail  string // 添加人邮箱
	LinkPhone  string // 添加人联系电话
	ClickCount string // 点击量
	Enabled    string // 是否显示
	Orderby    string // 排序
	Target     string // 是否开启浏览器新窗口
	Bgcolor    string // 背景颜色
}

// kcodeAdColumns holds the columns for table kcode_ad.
var kcodeAdColumns = KcodeAdColumns{
	AdId:       "ad_id",
	Pid:        "pid",
	MediaType:  "media_type",
	AdName:     "ad_name",
	AdLink:     "ad_link",
	AdCode:     "ad_code",
	StartTime:  "start_time",
	EndTime:    "end_time",
	LinkMan:    "link_man",
	LinkEmail:  "link_email",
	LinkPhone:  "link_phone",
	ClickCount: "click_count",
	Enabled:    "enabled",
	Orderby:    "orderby",
	Target:     "target",
	Bgcolor:    "bgcolor",
}

// NewKcodeAdDao creates and returns a new DAO object for table data access.
func NewKcodeAdDao() *KcodeAdDao {
	return &KcodeAdDao{
		group:   "default",
		table:   "kcode_ad",
		columns: kcodeAdColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KcodeAdDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KcodeAdDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KcodeAdDao) Columns() KcodeAdColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KcodeAdDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KcodeAdDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KcodeAdDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
