// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeAdminIconDao is the data access object for table kcode_admin_icon.
type KcodeAdminIconDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns KcodeAdminIconColumns // columns contains all the column names of Table for convenient usage.
}

// KcodeAdminIconColumns defines and stores column names for table kcode_admin_icon.
type KcodeAdminIconColumns struct {
	Id         string //
	Name       string // 图标名称
	Url        string // 图标css地址
	Prefix     string // 图标前缀
	FontFamily string // 字体名
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	Status     string // 状态
}

// kcodeAdminIconColumns holds the columns for table kcode_admin_icon.
var kcodeAdminIconColumns = KcodeAdminIconColumns{
	Id:         "id",
	Name:       "name",
	Url:        "url",
	Prefix:     "prefix",
	FontFamily: "font_family",
	CreateTime: "create_time",
	UpdateTime: "update_time",
	Status:     "status",
}

// NewKcodeAdminIconDao creates and returns a new DAO object for table data access.
func NewKcodeAdminIconDao() *KcodeAdminIconDao {
	return &KcodeAdminIconDao{
		group:   "default",
		table:   "kcode_admin_icon",
		columns: kcodeAdminIconColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KcodeAdminIconDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KcodeAdminIconDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KcodeAdminIconDao) Columns() KcodeAdminIconColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KcodeAdminIconDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KcodeAdminIconDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KcodeAdminIconDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
