// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KcodeChainDao is the data access object for table kcode_chain.
type KcodeChainDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns KcodeChainColumns // columns contains all the column names of Table for convenient usage.
}

// KcodeChainColumns defines and stores column names for table kcode_chain.
type KcodeChainColumns struct {
	Id     string //
	Name   string // 链名称
	TypeId string // 链类型（1=erc20，2=trc20）
}

// kcodeChainColumns holds the columns for table kcode_chain.
var kcodeChainColumns = KcodeChainColumns{
	Id:     "id",
	Name:   "name",
	TypeId: "type_id",
}

// NewKcodeChainDao creates and returns a new DAO object for table data access.
func NewKcodeChainDao() *KcodeChainDao {
	return &KcodeChainDao{
		group:   "default",
		table:   "kcode_chain",
		columns: kcodeChainColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KcodeChainDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KcodeChainDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KcodeChainDao) Columns() KcodeChainColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KcodeChainDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KcodeChainDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KcodeChainDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
