
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name: "mall"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: ""
  # dao生成
  gen:
    dao: # todo 换成自己的数据库
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/bvt"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
