// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"learn_goframe01/internal/model"
)

type (
	IUser interface {
		UserLogin(ctx context.Context, in model.UserCreateInput) (out model.UserCreateOutput, err error)
		Register(ctx context.Context, account string) (int, error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
