// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdDao is internal type for wrapping internal DAO implements.
type internalKcodeAdDao = *internal.KcodeAdDao

// kcodeAdDao is the data access object for table kcode_ad.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdDao struct {
	internalKcodeAdDao
}

var (
	// KcodeAd is globally public accessible object for table kcode_ad operations.
	KcodeAd = kcodeAdDao{
		internal.NewKcodeAdDao(),
	}
)

// Fill with you ideas below.
