// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminHookPluginDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminHookPluginDao = *internal.KcodeAdminHookPluginDao

// kcodeAdminHookPluginDao is the data access object for table kcode_admin_hook_plugin.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminHookPluginDao struct {
	internalKcodeAdminHookPluginDao
}

var (
	// KcodeAdminHookPlugin is globally public accessible object for table kcode_admin_hook_plugin operations.
	KcodeAdminHookPlugin = kcodeAdminHookPluginDao{
		internal.NewKcodeAdminHookPluginDao(),
	}
)

// Fill with you ideas below.
