// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminAccessDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminAccessDao = *internal.KcodeAdminAccessDao

// kcodeAdminAccessDao is the data access object for table kcode_admin_access.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminAccessDao struct {
	internalKcodeAdminAccessDao
}

var (
	// KcodeAdminAccess is globally public accessible object for table kcode_admin_access operations.
	KcodeAdminAccess = kcodeAdminAccessDao{
		internal.NewKcodeAdminAccessDao(),
	}
)

// Fill with you ideas below.
