// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeSmsEmailLogDao is internal type for wrapping internal DAO implements.
type internalKcodeSmsEmailLogDao = *internal.KcodeSmsEmailLogDao

// kcodeSmsEmailLogDao is the data access object for table kcode_sms_email_log.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeSmsEmailLogDao struct {
	internalKcodeSmsEmailLogDao
}

var (
	// KcodeSmsEmailLog is globally public accessible object for table kcode_sms_email_log operations.
	KcodeSmsEmailLog = kcodeSmsEmailLogDao{
		internal.NewKcodeSmsEmailLogDao(),
	}
)

// Fill with you ideas below.
