// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeTrendDao is internal type for wrapping internal DAO implements.
type internalKcodeTrendDao = *internal.KcodeTrendDao

// kcodeTrendDao is the data access object for table kcode_trend.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeTrendDao struct {
	internalKcodeTrendDao
}

var (
	// KcodeTrend is globally public accessible object for table kcode_trend operations.
	KcodeTrend = kcodeTrendDao{
		internal.NewKcodeTrendDao(),
	}
)

// Fill with you ideas below.
