// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodePayTempDao is internal type for wrapping internal DAO implements.
type internalKcodePayTempDao = *internal.KcodePayTempDao

// kcodePayTempDao is the data access object for table kcode_pay_temp.
// You can define custom methods on it to extend its functionality as you wish.
type kcodePayTempDao struct {
	internalKcodePayTempDao
}

var (
	// KcodePayTemp is globally public accessible object for table kcode_pay_temp operations.
	KcodePayTemp = kcodePayTempDao{
		internal.NewKcodePayTempDao(),
	}
)

// Fill with you ideas below.
