// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserLoginLogDao is internal type for wrapping internal DAO implements.
type internalKcodeUserLoginLogDao = *internal.KcodeUserLoginLogDao

// kcodeUserLoginLogDao is the data access object for table kcode_user_login_log.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserLoginLogDao struct {
	internalKcodeUserLoginLogDao
}

var (
	// KcodeUserLoginLog is globally public accessible object for table kcode_user_login_log operations.
	KcodeUserLoginLog = kcodeUserLoginLogDao{
		internal.NewKcodeUserLoginLogDao(),
	}
)

// Fill with you ideas below.
