// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserDao is internal type for wrapping internal DAO implements.
type internalKcodeUserDao = *internal.KcodeUserDao

// kcodeUserDao is the data access object for table kcode_user.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserDao struct {
	internalKcodeUserDao
}

var (
	// KcodeUser is globally public accessible object for table kcode_user operations.
	KcodeUser = kcodeUserDao{
		internal.NewKcodeUserDao(),
	}
)

// Fill with you ideas below.
