// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserJobDao is internal type for wrapping internal DAO implements.
type internalKcodeUserJobDao = *internal.KcodeUserJobDao

// kcodeUserJobDao is the data access object for table kcode_user_job.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserJobDao struct {
	internalKcodeUserJobDao
}

var (
	// KcodeUserJob is globally public accessible object for table kcode_user_job operations.
	KcodeUserJob = kcodeUserJobDao{
		internal.NewKcodeUserJobDao(),
	}
)

// Fill with you ideas below.
