// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeJobOrderDao is internal type for wrapping internal DAO implements.
type internalKcodeJobOrderDao = *internal.KcodeJobOrderDao

// kcodeJobOrderDao is the data access object for table kcode_job_order.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeJobOrderDao struct {
	internalKcodeJobOrderDao
}

var (
	// KcodeJobOrder is globally public accessible object for table kcode_job_order operations.
	KcodeJobOrder = kcodeJobOrderDao{
		internal.NewKcodeJobOrderDao(),
	}
)

// Fill with you ideas below.
