// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserBonusCensusDao is internal type for wrapping internal DAO implements.
type internalKcodeUserBonusCensusDao = *internal.KcodeUserBonusCensusDao

// kcodeUserBonusCensusDao is the data access object for table kcode_user_bonus_census.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserBonusCensusDao struct {
	internalKcodeUserBonusCensusDao
}

var (
	// KcodeUserBonusCensus is globally public accessible object for table kcode_user_bonus_census operations.
	KcodeUserBonusCensus = kcodeUserBonusCensusDao{
		internal.NewKcodeUserBonusCensusDao(),
	}
)

// Fill with you ideas below.
