// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeNewsDao is internal type for wrapping internal DAO implements.
type internalKcodeNewsDao = *internal.KcodeNewsDao

// kcodeNewsDao is the data access object for table kcode_news.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeNewsDao struct {
	internalKcodeNewsDao
}

var (
	// KcodeNews is globally public accessible object for table kcode_news operations.
	KcodeNews = kcodeNewsDao{
		internal.NewKcodeNewsDao(),
	}
)

// Fill with you ideas below.
