// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminConfigDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminConfigDao = *internal.KcodeAdminConfigDao

// kcodeAdminConfigDao is the data access object for table kcode_admin_config.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminConfigDao struct {
	internalKcodeAdminConfigDao
}

var (
	// KcodeAdminConfig is globally public accessible object for table kcode_admin_config operations.
	KcodeAdminConfig = kcodeAdminConfigDao{
		internal.NewKcodeAdminConfigDao(),
	}
)

// Fill with you ideas below.
