// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserUpLogDao is internal type for wrapping internal DAO implements.
type internalKcodeUserUpLogDao = *internal.KcodeUserUpLogDao

// kcodeUserUpLogDao is the data access object for table kcode_user_up_log.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserUpLogDao struct {
	internalKcodeUserUpLogDao
}

var (
	// KcodeUserUpLog is globally public accessible object for table kcode_user_up_log operations.
	KcodeUserUpLog = kcodeUserUpLogDao{
		internal.NewKcodeUserUpLogDao(),
	}
)

// Fill with you ideas below.
