// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdPositionDao is internal type for wrapping internal DAO implements.
type internalKcodeAdPositionDao = *internal.KcodeAdPositionDao

// kcodeAdPositionDao is the data access object for table kcode_ad_position.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdPositionDao struct {
	internalKcodeAdPositionDao
}

var (
	// KcodeAdPosition is globally public accessible object for table kcode_ad_position operations.
	KcodeAdPosition = kcodeAdPositionDao{
		internal.NewKcodeAdPositionDao(),
	}
)

// Fill with you ideas below.
