// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserInfoDao is internal type for wrapping internal DAO implements.
type internalKcodeUserInfoDao = *internal.KcodeUserInfoDao

// kcodeUserInfoDao is the data access object for table kcode_user_info.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserInfoDao struct {
	internalKcodeUserInfoDao
}

var (
	// KcodeUserInfo is globally public accessible object for table kcode_user_info operations.
	KcodeUserInfo = kcodeUserInfoDao{
		internal.NewKcodeUserInfoDao(),
	}
)

// Fill with you ideas below.
