// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserRechargeDao is internal type for wrapping internal DAO implements.
type internalKcodeUserRechargeDao = *internal.KcodeUserRechargeDao

// kcodeUserRechargeDao is the data access object for table kcode_user_recharge.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserRechargeDao struct {
	internalKcodeUserRechargeDao
}

var (
	// KcodeUserRecharge is globally public accessible object for table kcode_user_recharge operations.
	KcodeUserRecharge = kcodeUserRechargeDao{
		internal.NewKcodeUserRechargeDao(),
	}
)

// Fill with you ideas below.
