// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminPluginDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminPluginDao = *internal.KcodeAdminPluginDao

// kcodeAdminPluginDao is the data access object for table kcode_admin_plugin.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminPluginDao struct {
	internalKcodeAdminPluginDao
}

var (
	// KcodeAdminPlugin is globally public accessible object for table kcode_admin_plugin operations.
	KcodeAdminPlugin = kcodeAdminPluginDao{
		internal.NewKcodeAdminPluginDao(),
	}
)

// Fill with you ideas below.
