// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserTokenDao is internal type for wrapping internal DAO implements.
type internalKcodeUserTokenDao = *internal.KcodeUserTokenDao

// kcodeUserTokenDao is the data access object for table kcode_user_token.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserTokenDao struct {
	internalKcodeUserTokenDao
}

var (
	// KcodeUserToken is globally public accessible object for table kcode_user_token operations.
	KcodeUserToken = kcodeUserTokenDao{
		internal.NewKcodeUserTokenDao(),
	}
)

// Fill with you ideas below.
