// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeCensusLogDao is internal type for wrapping internal DAO implements.
type internalKcodeCensusLogDao = *internal.KcodeCensusLogDao

// kcodeCensusLogDao is the data access object for table kcode_census_log.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeCensusLogDao struct {
	internalKcodeCensusLogDao
}

var (
	// KcodeCensusLog is globally public accessible object for table kcode_census_log operations.
	KcodeCensusLog = kcodeCensusLogDao{
		internal.NewKcodeCensusLogDao(),
	}
)

// Fill with you ideas below.
