// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserMoneyTypeDao is internal type for wrapping internal DAO implements.
type internalKcodeUserMoneyTypeDao = *internal.KcodeUserMoneyTypeDao

// kcodeUserMoneyTypeDao is the data access object for table kcode_user_money_type.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserMoneyTypeDao struct {
	internalKcodeUserMoneyTypeDao
}

var (
	// KcodeUserMoneyType is globally public accessible object for table kcode_user_money_type operations.
	KcodeUserMoneyType = kcodeUserMoneyTypeDao{
		internal.NewKcodeUserMoneyTypeDao(),
	}
)

// Fill with you ideas below.
