// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminActionDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminActionDao = *internal.KcodeAdminActionDao

// kcodeAdminActionDao is the data access object for table kcode_admin_action.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminActionDao struct {
	internalKcodeAdminActionDao
}

var (
	// KcodeAdminAction is globally public accessible object for table kcode_admin_action operations.
	KcodeAdminAction = kcodeAdminActionDao{
		internal.NewKcodeAdminActionDao(),
	}
)

// Fill with you ideas below.
