// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminUserDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminUserDao = *internal.KcodeAdminUserDao

// kcodeAdminUserDao is the data access object for table kcode_admin_user.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminUserDao struct {
	internalKcodeAdminUserDao
}

var (
	// KcodeAdminUser is globally public accessible object for table kcode_admin_user operations.
	KcodeAdminUser = kcodeAdminUserDao{
		internal.NewKcodeAdminUserDao(),
	}
)

// Fill with you ideas below.
