// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeChainDao is internal type for wrapping internal DAO implements.
type internalKcodeChainDao = *internal.KcodeChainDao

// kcodeChainDao is the data access object for table kcode_chain.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeChainDao struct {
	internalKcodeChainDao
}

var (
	// KcodeChain is globally public accessible object for table kcode_chain operations.
	KcodeChain = kcodeChainDao{
		internal.NewKcodeChainDao(),
	}
)

// Fill with you ideas below.
