// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserMessageDao is internal type for wrapping internal DAO implements.
type internalKcodeUserMessageDao = *internal.KcodeUserMessageDao

// kcodeUserMessageDao is the data access object for table kcode_user_message.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserMessageDao struct {
	internalKcodeUserMessageDao
}

var (
	// KcodeUserMessage is globally public accessible object for table kcode_user_message operations.
	KcodeUserMessage = kcodeUserMessageDao{
		internal.NewKcodeUserMessageDao(),
	}
)

// Fill with you ideas below.
