// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserMoneyLogDao is internal type for wrapping internal DAO implements.
type internalKcodeUserMoneyLogDao = *internal.KcodeUserMoneyLogDao

// kcodeUserMoneyLogDao is the data access object for table kcode_user_money_log.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserMoneyLogDao struct {
	internalKcodeUserMoneyLogDao
}

var (
	// KcodeUserMoneyLog is globally public accessible object for table kcode_user_money_log operations.
	KcodeUserMoneyLog = kcodeUserMoneyLogDao{
		internal.NewKcodeUserMoneyLogDao(),
	}
)

// Fill with you ideas below.
