// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeInvestFuelDao is internal type for wrapping internal DAO implements.
type internalKcodeInvestFuelDao = *internal.KcodeInvestFuelDao

// kcodeInvestFuelDao is the data access object for table kcode_invest_fuel.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeInvestFuelDao struct {
	internalKcodeInvestFuelDao
}

var (
	// KcodeInvestFuel is globally public accessible object for table kcode_invest_fuel operations.
	KcodeInvestFuel = kcodeInvestFuelDao{
		internal.NewKcodeInvestFuelDao(),
	}
)

// Fill with you ideas below.
