// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeUserMoneyDao is internal type for wrapping internal DAO implements.
type internalKcodeUserMoneyDao = *internal.KcodeUserMoneyDao

// kcodeUserMoneyDao is the data access object for table kcode_user_money.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeUserMoneyDao struct {
	internalKcodeUserMoneyDao
}

var (
	// KcodeUserMoney is globally public accessible object for table kcode_user_money operations.
	KcodeUserMoney = kcodeUserMoneyDao{
		internal.NewKcodeUserMoneyDao(),
	}
)

// Fill with you ideas below.
