// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminPacketDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminPacketDao = *internal.KcodeAdminPacketDao

// kcodeAdminPacketDao is the data access object for table kcode_admin_packet.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminPacketDao struct {
	internalKcodeAdminPacketDao
}

var (
	// KcodeAdminPacket is globally public accessible object for table kcode_admin_packet operations.
	KcodeAdminPacket = kcodeAdminPacketDao{
		internal.NewKcodeAdminPacketDao(),
	}
)

// Fill with you ideas below.
