// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"learn_goframe01/internal/dao/internal"
)

// internalKcodeAdminModuleDao is internal type for wrapping internal DAO implements.
type internalKcodeAdminModuleDao = *internal.KcodeAdminModuleDao

// kcodeAdminModuleDao is the data access object for table kcode_admin_module.
// You can define custom methods on it to extend its functionality as you wish.
type kcodeAdminModuleDao struct {
	internalKcodeAdminModuleDao
}

var (
	// KcodeAdminModule is globally public accessible object for table kcode_admin_module operations.
	KcodeAdminModule = kcodeAdminModuleDao{
		internal.NewKcodeAdminModuleDao(),
	}
)

// Fill with you ideas below.
