// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserMessage is the golang structure for table kcode_user_message.
type KcodeUserMessage struct {
	Id         uint64 `json:"id"         description:""`
	UidReceive uint   `json:"uidReceive" description:"接收消息的用户id"`
	UidSend    uint   `json:"uidSend"    description:"发送消息的用户id"`
	Type       string `json:"type"       description:"消息分类"`
	Title      string `json:"title"      description:"发送的标题"`
	Content    string `json:"content"    description:"消息内容"`
	Status     uint   `json:"status"     description:"状态"`
	CreateTime uint   `json:"createTime" description:"创建时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	ReadTime   uint   `json:"readTime"   description:"阅读时间"`
}
