// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminConfig is the golang structure for table kcode_admin_config.
type KcodeAdminConfig struct {
	Id         uint   `json:"id"         description:""`
	Name       string `json:"name"       description:"名称"`
	Title      string `json:"title"      description:"标题"`
	Group      string `json:"group"      description:"配置分组"`
	Type       string `json:"type"       description:"类型"`
	Value      string `json:"value"      description:"配置值"`
	Options    string `json:"options"    description:"配置项"`
	Tips       string `json:"tips"       description:"配置提示"`
	AjaxUrl    string `json:"ajaxUrl"    description:"联动下拉框ajax地址"`
	NextItems  string `json:"nextItems"  description:"联动下拉框的下级下拉框名，多个以逗号隔开"`
	Param      string `json:"param"      description:"联动下拉框请求参数名"`
	Format     string `json:"format"     description:"格式，用于格式文本"`
	Table      string `json:"table"      description:"表名，只用于快速联动类型"`
	Level      uint   `json:"level"      description:"联动级别，只用于快速联动类型"`
	Key        string `json:"key"        description:"键字段，只用于快速联动类型"`
	Option     string `json:"option"     description:"值字段，只用于快速联动类型"`
	Pid        string `json:"pid"        description:"父级id字段，只用于快速联动类型"`
	Ak         string `json:"ak"         description:"百度地图appkey"`
	CreateTime uint   `json:"createTime" description:"创建时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	Sort       int    `json:"sort"       description:"排序"`
	Status     int    `json:"status"     description:"状态：0禁用，1启用"`
}
