// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminHookPlugin is the golang structure for table kcode_admin_hook_plugin.
type KcodeAdminHookPlugin struct {
	Id         uint   `json:"id"         description:""`
	Hook       string `json:"hook"       description:"钩子id"`
	Plugin     string `json:"plugin"     description:"插件标识"`
	CreateTime uint   `json:"createTime" description:"添加时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	Sort       uint   `json:"sort"       description:"排序"`
	Status     int    `json:"status"     description:"状态"`
}
