// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeWithdrawals is the golang structure for table kcode_withdrawals.
type KcodeWithdrawals struct {
	Id           int     `json:"id"           description:"id"`
	UserId       int     `json:"userId"       description:"用户id"`
	AtmMoney     float64 `json:"atmMoney"     description:"申请金额"`
	AtmMoneyType int     `json:"atmMoneyType" description:"币种类型"`
	TaxFee       float64 `json:"taxFee"       description:"税收手续费"`
	Money        float64 `json:"money"        description:"到账金额"`
	Status       int     `json:"status"       description:"状态：0申请中1审核通过2审核失败"`
	TransStatus  int     `json:"transStatus"  description:"'待确认','已到账','到账失败'"`
	CreateTime   int     `json:"createTime"   description:"申请时间"`
	CheckTime    int     `json:"checkTime"    description:"审核时间"`
	RefuseTime   int     `json:"refuseTime"   description:"拒绝时间"`
	AtmAddress   string  `json:"atmAddress"   description:"转账钱包地址"`
	ChainName    string  `json:"chainName"    description:"链名称"`
	AtmQrCode    string  `json:"atmQrCode"    description:"二维码"`
	Hash         string  `json:"hash"         description:""`
	Chain        int     `json:"chain"        description:"链ID"`
	ErrorMsg     string  `json:"errorMsg"     description:""`
}
