// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminAccess is the golang structure for table kcode_admin_access.
type KcodeAdminAccess struct {
	Module string `json:"module" description:"模型名称"`
	Group  string `json:"group"  description:"权限分组标识"`
	Uid    uint   `json:"uid"    description:"用户id"`
	Nid    string `json:"nid"    description:"授权节点id"`
	Tag    string `json:"tag"    description:"分组标签"`
}
