// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserJob is the golang structure for table kcode_user_job.
type KcodeUserJob struct {
	GroupId          uint    `json:"groupId"          description:"级别id"`
	GroupName        string  `json:"groupName"        description:"级别名称"`
	Zhituibili       float64 `json:"zhituibili"       description:"直推比例"`
	GroupNameEn      string  `json:"groupNameEn"      description:"级别名称"`
	ContentEn        string  `json:"contentEn"        description:"内容"`
	Price            float64 `json:"price"            description:"节点价格"`
	UsdtBonus        float64 `json:"usdtBonus"        description:"节点分红余额"`
	EndBonusTime     int     `json:"endBonusTime"     description:"最后分红时间"`
	Num              int     `json:"num"              description:"名额人数"`
	Content          string  `json:"content"          description:"内容"`
	Count            int     `json:"count"            description:"已购买数量"`
	InvestMoney      float64 `json:"investMoney"      description:"质押金额"`
	NetworkBonus     float64 `json:"networkBonus"     description:"全网加权分红百分比"`
	EquityBonus      float64 `json:"equityBonus"      description:"权益分红百分比"`
	OldGroupId       int     `json:"oldGroupId"       description:""`
	Logo             string  `json:"logo"             description:""`
	NetworkBonusPond float64 `json:"networkBonusPond" description:"全网加权分红池子"`
	EquityBonusPond  float64 `json:"equityBonusPond"  description:"权益分红池子"`
	PjBonus          float64 `json:"pjBonus"          description:"平级奖"`
	Status           int     `json:"status"           description:"1开放0不开放"`
}
