// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminPlugin is the golang structure for table kcode_admin_plugin.
type KcodeAdminPlugin struct {
	Id          uint   `json:"id"          description:""`
	Name        string `json:"name"        description:"插件名称"`
	Title       string `json:"title"       description:"插件标题"`
	Icon        string `json:"icon"        description:"图标"`
	Description string `json:"description" description:"插件描述"`
	Author      string `json:"author"      description:"作者"`
	AuthorUrl   string `json:"authorUrl"   description:"作者主页"`
	Config      string `json:"config"      description:"配置信息"`
	Version     string `json:"version"     description:"版本号"`
	Identifier  string `json:"identifier"  description:"插件唯一标识符"`
	Admin       uint   `json:"admin"       description:"是否有后台管理"`
	CreateTime  uint   `json:"createTime"  description:"安装时间"`
	UpdateTime  int    `json:"updateTime"  description:"更新时间"`
	Sort        int    `json:"sort"        description:"排序"`
	Status      int    `json:"status"      description:"状态"`
}
