// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserLog is the golang structure for table kcode_user_log.
type KcodeUserLog struct {
	Id      uint   `json:"id"      description:""`
	UserId  int    `json:"userId"  description:""`
	Msg     string `json:"msg"     description:"用户操作信息"`
	AddTime int    `json:"addTime" description:"添加时间"`
}
