// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserGroupBonus is the golang structure for table kcode_user_group_bonus.
type KcodeUserGroupBonus struct {
	Id         uint    `json:"id"         description:""`
	GroupId    int     `json:"groupId"    description:"级别"`
	Floor      int     `json:"floor"      description:"层级"`
	BonusMoney float64 `json:"bonusMoney" description:"奖金比例"`
}
