// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserToken is the golang structure for table kcode_user_token.
type KcodeUserToken struct {
	Id           uint   `json:"id"           description:""`
	UserId       int    `json:"userId"       description:"用户userid"`
	Token        string `json:"token"        description:""`
	LoginTime    uint   `json:"loginTime"    description:"登录时间"`
	LoginIp      string `json:"loginIp"      description:"登录IP地址"`
	LoginOs      string `json:"loginOs"      description:"登录操作系统"`
	LoginBrowser string `json:"loginBrowser" description:"登录浏览器"`
	ExpireTime   uint   `json:"expireTime"   description:"有效期"`
	LoginType    string `json:"loginType"    description:"登录类型 0 未知 1 网页 2.移动端网页 3.app"`
}
