// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeNews is the golang structure for table kcode_news.
type KcodeNews struct {
	Id         int    `json:"id"         description:""`
	TypeId     uint   `json:"typeId"     description:"类型ID"`
	Title      string `json:"title"      description:"标题"`
	TitleEn    string `json:"titleEn"    description:""`
	TitleTw    string `json:"titleTw"    description:""`
	Keysword   string `json:"keysword"   description:"关键词"`
	Introduce  string `json:"introduce"  description:"介绍"`
	ContentEn  string `json:"contentEn"  description:"英文介绍"`
	ContentTw  string `json:"contentTw"  description:"繁体介绍"`
	Content    string `json:"content"    description:"新闻内容"`
	Sort       uint   `json:"sort"       description:"排序"`
	CreateTime uint   `json:"createTime" description:"添加日期"`
	UpdateTime uint   `json:"updateTime" description:"修改日期"`
	Status     uint   `json:"status"     description:"1开启 0关闭"`
	Addperson  string `json:"addperson"  description:"添加者"`
	Flag       string `json:"flag"       description:"文章属性"`
	Click      uint   `json:"click"      description:"点击数量"`
	Image      string `json:"image"      description:"公共的图片地址"`
	PcImage    string `json:"pcImage"    description:"pc缩略图"`
	WapImage   string `json:"wapImage"   description:"手机端缩略图"`
	JumpUrl    string `json:"jumpUrl"    description:"跳转的地址,如果不填，讲会跳转到平台自己的地址"`
	IsIndex    int    `json:"isIndex"    description:"是否显示在首页，0=不显示，1=显示"`
}
