// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserMoney is the golang structure for table kcode_user_money.
type KcodeUserMoney struct {
	Id               uint    `json:"id"               description:""`
	UserId           int     `json:"userId"           description:""`
	AMoney           float64 `json:"aMoney"           description:""`
	UsdtMoney        float64 `json:"usdtMoney"        description:""`
	BMoney           float64 `json:"bMoney"           description:""`
	SetLastTime      int     `json:"setLastTime"      description:"最后结算的时间"`
	SetLastDate      int     `json:"setLastDate"      description:"最后结算的日期"`
	SetDayTime       int     `json:"setDayTime"       description:"订单下次可以结算的日期"`
	ReturnCountDay   int     `json:"returnCountDay"   description:"已经发放天数"`
	ReturnCountMoney float64 `json:"returnCountMoney" description:"发放总额"`
	ReturnMaxDay     float64 `json:"returnMaxDay"     description:"发放天数"`
	Status           int     `json:"status"           description:"私募奖励发放是否到期"`
	MoneyId          int     `json:"moneyId"          description:"币种id"`
	Balance          float64 `json:"balance"          description:""`
}
