// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserMoneyLog is the golang structure for table kcode_user_money_log.
type KcodeUserMoneyLog struct {
	LogId         uint    `json:"logId"         description:"自增编号"`
	UserId        uint    `json:"userId"        description:"用户user_id"`
	MoneyType     int     `json:"moneyType"     description:"币种类型 关联money_type 表"`
	Money         float64 `json:"money"         description:"变化的金额"`
	MoneyAction   string  `json:"moneyAction"   description:"增加还是减少 默认+"`
	Balance       float64 `json:"balance"       description:"余下额度"`
	Messages      string  `json:"messages"      description:"交易信息"`
	LangVal       string  `json:"langVal"       description:"语言键值"`
	MessagesLang  string  `json:"messagesLang"  description:"语言内容"`
	AddTime       uint    `json:"addTime"       description:"添加时间"`
	ParentId      uint    `json:"parentId"      description:"父ID"`
	Status        int     `json:"status"        description:"状态 0 未成功 1成功"`
	PayTime       uint    `json:"payTime"       description:"支付时间"`
	OperationType int     `json:"operationType" description:"操作类型"`
	BonusType     uint    `json:"bonusType"     description:"奖金类型，1直推奖励 2团队奖励3全网加权分红4权益分红"`
	EndTime       int     `json:"endTime"       description:"结算时间"`
	CoinPrice     float64 `json:"coinPrice"     description:"当前币价"`
	Usdt          float64 `json:"usdt"          description:"usdt"`
}
