// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserGroup is the golang structure for table kcode_user_group.
type KcodeUserGroup struct {
	GroupId          uint    `json:"groupId"          description:"级别id"`
	GroupName        string  `json:"groupName"        description:"级别名称"`
	UpZtNum          int     `json:"upZtNum"          description:"升级需要的直推人数"`
	ZtBuyNum         int     `json:"ztBuyNum"         description:"直推业绩"`
	BuyNum           int     `json:"buyNum"           description:"升级需要的个人业绩"`
	TeamBuyNum       int     `json:"teamBuyNum"       description:"升级需要的团队业绩"`
	UpTeamNum        int     `json:"upTeamNum"        description:"升级需要的团队人数"`
	UpTeamGroup      int     `json:"upTeamGroup"      description:"升级需要的团队会员级别要求"`
	TeamBonus        float64 `json:"teamBonus"        description:"团队奖比例"`
	ZtValidAccount   int     `json:"ztValidAccount"   description:"直推有效账号人数"`
	ShareProfits     float64 `json:"shareProfits"     description:"分红"`
	CreateTime       uint    `json:"createTime"       description:"创建时间"`
	UpdateTime       uint    `json:"updateTime"       description:"最后更新时间"`
	TeamProfitsFloor string  `json:"teamProfitsFloor" description:"团队奖层级奖励"`
	ExchangeFee      float64 `json:"exchangeFee"      description:"内部交易所手续费"`
	RewardRules      string  `json:"rewardRules"      description:"奖励规则"`
	Logo             string  `json:"logo"             description:""`
}
