// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodePayTemp is the golang structure for table kcode_pay_temp.
type KcodePayTemp struct {
	Id              int     `json:"id"              description:""`
	UserId          int     `json:"userId"          description:""`
	AddTime         int     `json:"addTime"         description:""`
	Method          string  `json:"method"          description:""`
	Param           string  `json:"param"           description:""`
	Status          int     `json:"status"          description:""`
	Money           float64 `json:"money"           description:""`
	ContractAddress string  `json:"contractAddress" description:"合约地址"`
	WalletAddress   string  `json:"walletAddress"   description:"收款钱包"`
	Hash            string  `json:"hash"            description:"此hash前端传2时有"`
}
