// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeTrend is the golang structure for table kcode_trend.
type KcodeTrend struct {
	Id        int     `json:"id"        description:""`
	MoneyType int     `json:"moneyType" description:""`
	Today     string  `json:"today"     description:""`
	Hour      int     `json:"hour"      description:""`
	V         float64 `json:"v"         description:"开盘价"`
}
