// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminIcon is the golang structure for table kcode_admin_icon.
type KcodeAdminIcon struct {
	Id         uint   `json:"id"         description:""`
	Name       string `json:"name"       description:"图标名称"`
	Url        string `json:"url"        description:"图标css地址"`
	Prefix     string `json:"prefix"     description:"图标前缀"`
	FontFamily string `json:"fontFamily" description:"字体名"`
	CreateTime uint   `json:"createTime" description:"创建时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	Status     uint   `json:"status"     description:"状态"`
}
