// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeInvestPledgeOrder is the golang structure for table kcode_invest_pledge_order.
type KcodeInvestPledgeOrder struct {
	OrderId         int     `json:"orderId"         description:""`
	AddTime         int     `json:"addTime"         description:""`
	OrderSn         string  `json:"orderSn"         description:""`
	UserId          int     `json:"userId"          description:""`
	PayStatus       int     `json:"payStatus"       description:"1已支付0未支付"`
	MoneyType       int     `json:"moneyType"       description:""`
	OrderMoney      float64 `json:"orderMoney"      description:"投资金额"`
	OrderType       int     `json:"orderType"       description:"1质押 2激活"`
	ExpandNum       int     `json:"expandNum"       description:"收益倍数"`
	TokenDayMoney   float64 `json:"tokenDayMoney"   description:"今日收益"`
	TokenCountMoney float64 `json:"tokenCountMoney" description:"累计收益"`
	ReturnCountDay  int     `json:"returnCountDay"  description:"累计释放天数"`
	SetDayTime      int     `json:"setDayTime"      description:"最后释放时间"`
	Status          int     `json:"status"          description:"1质押中 0闲置中 2已赎回 3已分红完"`
	PayHash         string  `json:"payHash"         description:"付款hash"`
	PayTime         int     `json:"payTime"         description:"付款时间"`
	RedeTime        int     `json:"redeTime"        description:"赎回时间"`
	HashRemark      string  `json:"hashRemark"      description:""`
	TotalIncome     float64 `json:"totalIncome"     description:"翻倍后总收益"`
	TopOrderId      int     `json:"topOrderId"      description:""`
	ResidualIncome  float64 `json:"residualIncome"  description:"剩余收益"`
	OrderUsdt       float64 `json:"orderUsdt"       description:"实际投资USDT"`
	Hash            string  `json:"hash"            description:"付款hash"`
	CoinPrice       float64 `json:"coinPrice"       description:"当前比价"`
	UsdtMoney       float64 `json:"usdtMoney"       description:"新版记录（仅页面回显用到）"`
	TotalIncomeUsdt float64 `json:"totalIncomeUsdt" description:"总收益 U"`
	ResidualUsdt    float64 `json:"residualUsdt"    description:"剩余收益 u"`
	Line            int     `json:"line"            description:"1排队中 0未排队"`
	PaiTime         int     `json:"paiTime"         description:"排队时间"`
}
