// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAd is the golang structure for table kcode_ad.
type KcodeAd struct {
	AdId       uint   `json:"adId"       description:"广告id"`
	Pid        uint   `json:"pid"        description:"广告位置ID"`
	MediaType  uint   `json:"mediaType"  description:"广告类型"`
	AdName     string `json:"adName"     description:"广告名称"`
	AdLink     string `json:"adLink"     description:"链接地址"`
	AdCode     string `json:"adCode"     description:"图片地址"`
	StartTime  int    `json:"startTime"  description:"投放时间"`
	EndTime    int    `json:"endTime"    description:"结束时间"`
	LinkMan    string `json:"linkMan"    description:"添加人"`
	LinkEmail  string `json:"linkEmail"  description:"添加人邮箱"`
	LinkPhone  string `json:"linkPhone"  description:"添加人联系电话"`
	ClickCount uint   `json:"clickCount" description:"点击量"`
	Enabled    uint   `json:"enabled"    description:"是否显示"`
	Orderby    int    `json:"orderby"    description:"排序"`
	Target     int    `json:"target"     description:"是否开启浏览器新窗口"`
	Bgcolor    string `json:"bgcolor"    description:"背景颜色"`
}
