// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserBonusCensus is the golang structure for table kcode_user_bonus_census.
type KcodeUserBonusCensus struct {
	Id           uint    `json:"id"           description:"主键"`
	UserId       uint    `json:"userId"       description:"用户id"`
	MoneyType    int     `json:"moneyType"    description:"币种类型"`
	ZhituiBonus  float64 `json:"zhituiBonus"  description:"直推奖励"`
	TeamBonus    float64 `json:"teamBonus"    description:"团队奖励"`
	WholeBonus   float64 `json:"wholeBonus"   description:"全网加权分红"`
	EquityBonus  float64 `json:"equityBonus"  description:"权益分红"`
	ReleaseBonus float64 `json:"releaseBonus" description:"释放收益"`
	PjBonus      float64 `json:"pjBonus"      description:"平级奖"`
}
