// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUser is the golang structure for table kcode_user.
type KcodeUser struct {
	UserId          uint    `json:"userId"          description:"用户user_id"`
	JobId           uint    `json:"jobId"           description:"节点级别"`
	GroupId         uint    `json:"groupId"         description:"会员级别"`
	InviterCode     string  `json:"inviterCode"     description:"邀请码"`
	UserType        int     `json:"userType"        description:"用户类型"`
	Address         string  `json:"address"         description:"用户钱包地址"`
	Username        string  `json:"username"        description:"用户名"`
	Nickname        string  `json:"nickname"        description:"昵称"`
	Salt            string  `json:"salt"            description:"密码加密字符"`
	Password        string  `json:"password"        description:"密码"`
	Payword         string  `json:"payword"         description:"支付密码"`
	Mobile          string  `json:"mobile"          description:"手机号码"`
	MobileBind      uint    `json:"mobileBind"      description:"是否绑定手机号码"`
	Email           string  `json:"email"           description:"用户邮箱地址"`
	EmailBind       uint    `json:"emailBind"       description:"是否绑定邮箱地址"`
	Avatar          int     `json:"avatar"          description:"头像"`
	RegIp           string  `json:"regIp"           description:"注册ip"`
	CreateTime      uint    `json:"createTime"      description:"注册时间"`
	UpdateTime      int     `json:"updateTime"      description:"最后更新时间"`
	LastLoginIp     string  `json:"lastLoginIp"     description:"最后登录IP"`
	LastLoginTime   int     `json:"lastLoginTime"   description:"最后登录时间"`
	OpenTime        uint    `json:"openTime"        description:"会员开通时间"`
	OpenStatus      int     `json:"openStatus"      description:"会员开通状态 0 未开通 1 已经开通"`
	InviterUsername string  `json:"inviterUsername" description:"邀请人用户名"`
	Inviters        string  `json:"inviters"        description:"邀请人集合"`
	InviterId       int     `json:"inviterId"       description:"邀请人id"`
	IsAtm           uint    `json:"isAtm"           description:"当前帐号是否可以提现 1 可以提现 0 不可以提现"`
	IsLogin         uint    `json:"isLogin"         description:"1 可以登录 0冻结禁止登录"`
	LoginNum        int     `json:"loginNum"        description:"登录次数"`
	Age             uint    `json:"age"             description:"年龄"`
	Sex             uint    `json:"sex"             description:"性别 0 保密 1 男 2 女"`
	AvatarImg       string  `json:"avatarImg"       description:"图片URL地址"`
	IsFrozen        int     `json:"isFrozen"        description:"0 默认 1 冻结"`
	IsDel           int     `json:"isDel"           description:"注销 0 是否删除  1 删除注销"`
	IsTeam          int     `json:"isTeam"          description:"是否绑定微信"`
	Floor           int     `json:"floor"           description:"层数"`
	ZtNum           int     `json:"ztNum"           description:"直推人数"`
	TeamNum         int     `json:"teamNum"         description:"团队人数"`
	BuyNum          float64 `json:"buyNum"          description:"累计投资USDT数量"`
	TeamBuyNum      int     `json:"teamBuyNum"      description:"团队累计投资USDT数量"`
	BuyNumUsdt      float64 `json:"buyNumUsdt"      description:"个人业绩（U）"`
	TeamBuyNumUsdt  float64 `json:"teamBuyNumUsdt"  description:"团队业绩（U）"`
	IfEffer         int     `json:"ifEffer"         description:"是否是有效用户"`
	IsAd            int     `json:"isAd"            description:"1今日看过广告"`
	TokenBuyNum     float64 `json:"tokenBuyNum"     description:"累计投资换算hvt数量"`
	Suanli          float64 `json:"suanli"          description:"用户算力"`
}
