// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminMenu is the golang structure for table kcode_admin_menu.
type KcodeAdminMenu struct {
	Id         uint   `json:"id"         description:""`
	Pid        uint   `json:"pid"        description:"上级菜单id"`
	Module     string `json:"module"     description:"模块名称"`
	Title      string `json:"title"      description:"菜单标题"`
	Icon       string `json:"icon"       description:"菜单图标"`
	UrlType    string `json:"urlType"    description:"链接类型（link：外链，module：模块）"`
	UrlValue   string `json:"urlValue"   description:"链接地址"`
	UrlTarget  string `json:"urlTarget"  description:"链接打开方式：_blank,_self"`
	OnlineHide uint   `json:"onlineHide" description:"网站上线后是否隐藏"`
	CreateTime uint   `json:"createTime" description:"创建时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	Sort       int    `json:"sort"       description:"排序"`
	SystemMenu uint   `json:"systemMenu" description:"是否为系统菜单，系统菜单不可删除"`
	Status     int    `json:"status"     description:"状态"`
	Params     string `json:"params"     description:"参数"`
}
