// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserInfo is the golang structure for table kcode_user_info.
type KcodeUserInfo struct {
	UserId uint `json:"userId" description:""`
	Sex    uint `json:"sex"    description:"0  保密 1 男 2女"`
}
