// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeChain is the golang structure for table kcode_chain.
type KcodeChain struct {
	Id     uint   `json:"id"     description:""`
	Name   string `json:"name"   description:"链名称"`
	TypeId string `json:"typeId" description:"链类型（1=erc20，2=trc20）"`
}
