// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminHook is the golang structure for table kcode_admin_hook.
type KcodeAdminHook struct {
	Id          uint   `json:"id"          description:""`
	Name        string `json:"name"        description:"钩子名称"`
	Plugin      string `json:"plugin"      description:"钩子来自哪个插件"`
	Description string `json:"description" description:"钩子描述"`
	System      uint   `json:"system"      description:"是否为系统钩子"`
	CreateTime  uint   `json:"createTime"  description:"创建时间"`
	UpdateTime  uint   `json:"updateTime"  description:"更新时间"`
	Status      int    `json:"status"      description:"状态"`
}
