// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserLoginLog is the golang structure for table kcode_user_login_log.
type KcodeUserLoginLog struct {
	LogId        uint   `json:"logId"        description:"自动编号log_id"`
	UserId       int    `json:"userId"       description:"用户User_id"`
	Username     string `json:"username"     description:"登录用户名字"`
	LoginTime    uint   `json:"loginTime"    description:"登录时间"`
	LoginIp      string `json:"loginIp"      description:"登录IP地址"`
	LoginType    string `json:"loginType"    description:"登录类型"`
	LoginOs      string `json:"loginOs"      description:"登录系统信息"`
	LoginBrowser string `json:"loginBrowser" description:""`
	LoginMsg     string `json:"loginMsg"     description:"登录提示信息"`
	Status       string `json:"status"       description:""`
}
