// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserMoneyType is the golang structure for table kcode_user_money_type.
type KcodeUserMoneyType struct {
	Id              uint    `json:"id"              description:""`
	Icon            int     `json:"icon"            description:"币种图标"`
	Name            string  `json:"name"            description:"币种英文标识"`
	EnName          string  `json:"enName"          description:"币种英文名字"`
	CnName          string  `json:"cnName"          description:"币种中文名字"`
	IsSystem        int     `json:"isSystem"        description:"系统变量"`
	IsTransfer      int     `json:"isTransfer"      description:"是否允许转账"`
	IsAdmRecharge   int     `json:"isAdmRecharge"   description:"是否允许后台充值"`
	IsUserRecharge  int     `json:"isUserRecharge"  description:"是否允许用户充值"`
	IsAtm           int     `json:"isAtm"           description:"是否可以提现"`
	ExchangeRate    float64 `json:"exchangeRate"    description:"币价（$）"`
	IsExchange      int     `json:"isExchange"      description:"是否可以兑换"`
	Status          int     `json:"status"          description:"状态 0禁用  1启用"`
	ContractAddress string  `json:"contractAddress" description:"代币合约地址"`
	MinAtmMoney     float64 `json:"minAtmMoney"     description:"最低提现金额"`
	AtmFee          float64 `json:"atmFee"          description:"提现手续费"`
	AtmTips         string  `json:"atmTips"         description:"提现说明"`
	TokenAbi        string  `json:"tokenAbi"        description:"币种的token_abi"`
	WithdrawRatio   float64 `json:"withdrawRatio"   description:"可提现比例"`
	WithdrawDays    int     `json:"withdrawDays"    description:"提现间隔天数"`
	Decimals        int     `json:"decimals"        description:"精度"`
	WalletAddress   string  `json:"walletAddress"   description:"收款钱包地址"`
	AutoMoeny       float64 `json:"autoMoeny"       description:"自动审核"`
	MaxAtmMoney     float64 `json:"maxAtmMoney"     description:"最高提现金额"`
	Date1           string  `json:"date1"           description:"提现开始时间"`
	Date2           string  `json:"date2"           description:"提现结束时间"`
	IsSell          int     `json:"isSell"          description:"是否开启出售"`
	SellPrice       float64 `json:"sellPrice"       description:"最低多少起售"`
	WithdrawAddress string  `json:"withdrawAddress" description:"提现钱包地址"`
	WithdrawKey     string  `json:"withdrawKey"     description:"提现钱包加密私钥"`
	Port            int     `json:"port"            description:"node服务断开（不能重复）"`
	Zhou            string  `json:"zhou"            description:"周提现"`
	RangeAbility    string  `json:"rangeAbility"    description:"涨跌幅"`
	TransactionPair string  `json:"transactionPair" description:"交易对"`
}
