// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminRole is the golang structure for table kcode_admin_role.
type KcodeAdminRole struct {
	Id            uint   `json:"id"            description:"角色id"`
	Pid           uint   `json:"pid"           description:"上级角色"`
	Name          string `json:"name"          description:"角色名称"`
	Description   string `json:"description"   description:"角色描述"`
	MenuAuth      string `json:"menuAuth"      description:"菜单权限"`
	Sort          int    `json:"sort"          description:"排序"`
	CreateTime    uint   `json:"createTime"    description:"创建时间"`
	UpdateTime    uint   `json:"updateTime"    description:"更新时间"`
	Status        int    `json:"status"        description:"状态"`
	Access        uint   `json:"access"        description:"是否可登录后台"`
	DefaultModule uint   `json:"defaultModule" description:"默认访问模块"`
}
