// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeInvestFuel is the golang structure for table kcode_invest_fuel.
type KcodeInvestFuel struct {
	Id              int     `json:"id"              description:""`
	AddTime         int     `json:"addTime"         description:""`
	UserId          int     `json:"userId"          description:""`
	TokenDayMoney   float64 `json:"tokenDayMoney"   description:"今日收益"`
	TokenCountMoney float64 `json:"tokenCountMoney" description:"累计收益"`
	ReturnCountDay  int     `json:"returnCountDay"  description:"累计释放天数"`
	SetDayTime      int     `json:"setDayTime"      description:"最后释放时间"`
	TotalIncome     float64 `json:"totalIncome"     description:"总收益"`
	ResidualIncome  float64 `json:"residualIncome"  description:"剩余收益"`
	UpdateTime      int     `json:"updateTime"      description:""`
	ProgressBar     float64 `json:"progressBar"     description:"进度条"`
}
