// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeSmsEmailLog is the golang structure for table kcode_sms_email_log.
type KcodeSmsEmailLog struct {
	Id           uint   `json:"id"           description:"记录ID"`
	Email        string `json:"email"        description:"用户邮箱"`
	Scene        int    `json:"scene"        description:"发送场景 1:用户注册,2:找回登录密码,3:找回资金密码,3:客户下单,4:客户支付,5:商家发货,6:实名验证' 7:退款成功"`
	Status       int    `json:"status"       description:"发送状态"`
	Code         string `json:"code"         description:"验证码"`
	Msg          string `json:"msg"          description:"发送短信内容"`
	AddTime      int    `json:"addTime"      description:"添加时间"`
	ValidityTime int    `json:"validityTime" description:"有效期"`
	Ip           string `json:"ip"           description:""`
	ErrorMsg     string `json:"errorMsg"     description:"发送短信异常内容"`
}
