// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminUser is the golang structure for table kcode_admin_user.
type KcodeAdminUser struct {
	Id            uint    `json:"id"            description:""`
	Username      string  `json:"username"      description:"用户名"`
	Nickname      string  `json:"nickname"      description:"昵称"`
	Password      string  `json:"password"      description:"密码"`
	Email         string  `json:"email"         description:"邮箱地址"`
	EmailBind     uint    `json:"emailBind"     description:"是否绑定邮箱地址"`
	Mobile        string  `json:"mobile"        description:"手机号码"`
	MobileBind    uint    `json:"mobileBind"    description:"是否绑定手机号码"`
	Avatar        uint    `json:"avatar"        description:"头像"`
	Money         float64 `json:"money"         description:"余额"`
	Score         uint    `json:"score"         description:"积分"`
	Role          uint    `json:"role"          description:"主角色ID"`
	Roles         string  `json:"roles"         description:"副角色ID"`
	Group         uint    `json:"group"         description:"部门id"`
	SignupIp      uint64  `json:"signupIp"      description:"注册ip"`
	CreateTime    uint    `json:"createTime"    description:"创建时间"`
	UpdateTime    uint    `json:"updateTime"    description:"更新时间"`
	LastLoginTime uint    `json:"lastLoginTime" description:"最后一次登录时间"`
	LastLoginIp   uint64  `json:"lastLoginIp"   description:"登录ip"`
	Sort          int     `json:"sort"          description:"排序"`
	Status        int     `json:"status"        description:"状态：0禁用，1启用"`
	Secret        string  `json:"secret"        description:"谷歌验证器秘钥"`
}
