// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminMessage is the golang structure for table kcode_admin_message.
type KcodeAdminMessage struct {
	Id         uint64 `json:"id"         description:""`
	UidReceive uint   `json:"uidReceive" description:"接收消息的用户id"`
	UidSend    uint   `json:"uidSend"    description:"发送消息的用户id"`
	Type       string `json:"type"       description:"消息分类"`
	Content    string `json:"content"    description:"消息内容"`
	Status     uint   `json:"status"     description:"状态"`
	CreateTime uint   `json:"createTime" description:"创建时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	ReadTime   uint   `json:"readTime"   description:"阅读时间"`
}
