// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminPacket is the golang structure for table kcode_admin_packet.
type KcodeAdminPacket struct {
	Id         uint   `json:"id"         description:""`
	Name       string `json:"name"       description:"数据包名"`
	Title      string `json:"title"      description:"数据包标题"`
	Author     string `json:"author"     description:"作者"`
	AuthorUrl  string `json:"authorUrl"  description:"作者url"`
	Version    string `json:"version"    description:""`
	Tables     string `json:"tables"     description:"数据表名"`
	CreateTime uint   `json:"createTime" description:"创建时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	Status     int    `json:"status"     description:"状态"`
}
