// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminAttachment is the golang structure for table kcode_admin_attachment.
type KcodeAdminAttachment struct {
	Id         uint   `json:"id"         description:""`
	Uid        uint   `json:"uid"        description:"用户id"`
	Name       string `json:"name"       description:"文件名"`
	Module     string `json:"module"     description:"模块名，由哪个模块上传的"`
	Path       string `json:"path"       description:"文件路径"`
	Thumb      string `json:"thumb"      description:"缩略图路径"`
	Url        string `json:"url"        description:"文件链接"`
	Mime       string `json:"mime"       description:"文件mime类型"`
	Ext        string `json:"ext"        description:"文件类型"`
	Size       uint   `json:"size"       description:"文件大小"`
	Md5        string `json:"md5"        description:"文件md5"`
	Sha1       string `json:"sha1"       description:"sha1 散列值"`
	Driver     string `json:"driver"     description:"上传驱动"`
	Download   uint   `json:"download"   description:"下载次数"`
	CreateTime uint   `json:"createTime" description:"上传时间"`
	UpdateTime uint   `json:"updateTime" description:"更新时间"`
	Sort       int    `json:"sort"       description:"排序"`
	Status     int    `json:"status"     description:"状态"`
	Width      uint   `json:"width"      description:"图片宽度"`
	Height     uint   `json:"height"     description:"图片高度"`
}
