// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeUserUpLog is the golang structure for table kcode_user_up_log.
type KcodeUserUpLog struct {
	Id             uint    `json:"id"             description:""`
	OldGroupId     int     `json:"oldGroupId"     description:""`
	NewGroupId     int     `json:"newGroupId"     description:""`
	UserId         int     `json:"userId"         description:"用户user_id"`
	ZtNum          int     `json:"ztNum"          description:"直推人数"`
	RefereeNum     int     `json:"refereeNum"     description:"推荐的数量"`
	BuyNum         float64 `json:"buyNum"         description:"个人业绩"`
	ZtBuyNum       float64 `json:"ztBuyNum"       description:"直推业绩"`
	CommunityMoney float64 `json:"communityMoney" description:"小区业绩"`
	Title          string  `json:"title"          description:"标题"`
	Content        string  `json:"content"        description:"内容"`
	AddTime        int     `json:"addTime"        description:"添加时间"`
}
