// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// KcodeAdminLog is the golang structure for table kcode_admin_log.
type KcodeAdminLog struct {
	Id         uint   `json:"id"         description:"主键"`
	ActionId   uint   `json:"actionId"   description:"行为id"`
	UserId     uint   `json:"userId"     description:"执行用户id"`
	ActionIp   int64  `json:"actionIp"   description:"执行行为者ip"`
	Model      string `json:"model"      description:"触发行为的表"`
	RecordId   uint   `json:"recordId"   description:"触发行为的数据id"`
	Remark     string `json:"remark"     description:"日志备注"`
	Status     int    `json:"status"     description:"状态"`
	CreateTime uint   `json:"createTime" description:"执行行为的时间"`
}
