// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id          uint        `json:"id"          description:"用户 ID"`
	Address     string      `json:"address"     description:"用户钱包地址"`
	InviterId   string      `json:"inviterId"   description:"邀请人id"`
	InviterCode string      `json:"inviterCode" description:"邀请码"`
	CreateAt    *gtime.Time `json:"createAt"    description:"创建时间"`
	UpdateAt    *gtime.Time `json:"updateAt"    description:"更新时间"`
}
